# Generated by Django 5.1.6 on 2025-03-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Splitz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_model',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
