# Generated by Django 5.1.6 on 2025-03-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Splitz', '0005_alter_splitmodel_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitmodel',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_expense', to='Splitz.expense_model'),
        ),
    ]
