# Generated by Django 5.1.6 on 2025-04-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Splitz', '0009_rename_am_receiver_balancemodel_amount_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemodel',
            name='amount_payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_payer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balancemodel',
            name='amount_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
